dds <- makeExampleDESeqDataSet(n=100, m=4)
expect_error(nbinomWaldTest(dds))
expect_error(nbinomLRT(dds))
dds <- estimateSizeFactors(dds)
dds <- estimateDispersions(dds)
mm <- model.matrix(~ condition, colData(dds))
mm0 <- model.matrix(~ 1, colData(dds))
expect_error(nbinomWaldTest(dds, betaPrior=TRUE, modelMatrix=mm))
expect_error(nbinomLRT(dds, betaPrior=TRUE, full=mm, reduced=mm0))
expect_error(nbinomWaldTest(dds, betaPrior=FALSE, modelMatrixType="expanded"))
expect_error(nbinomLRT(dds, betaPrior=FALSE, modelMatrixType="expanded"))
dds2 <- estimateMLEForBetaPriorVar(dds)
estimateBetaPriorVar(dds2, betaPriorMethod="quantile")
dds <- nbinomWaldTest(dds, modelMatrixType="standard")
covarianceMatrix(dds, 1)
